module.exports.auth = require('./auth.controller')
module.exports.orders = require('./orders.controller')
module.exports.blogs = require('./blogs.controller')
module.exports.users = require('./users.controller')
module.exports.addresses = require('./addresses.controller')
module.exports.cooperations = require('./cooperations.controller')
module.exports.withdrawals = require('./withdrawals.controller')
